### ISSUE TITLE
Build 420 - Breaking Change

### ISSUE THREAD

**Issue by wilirius** [mplodowski/logout-plugin#11]
With OctoberCMS Build 420, which includes Laravel 5.5, this plugin has (at least one) primary breaking issue. As of Laravel 5.4, Laravel doesn't use Symfony's SessionInterface, and instead implemented their own. The first error that I saw from this is in /middleware/ValidateSession.php line 66 calls getMetadataBag(), which doesn't exist in Laravel's implementation, nor do I see a way to access the last used.

**Comment by mplodowski** [comment]
Thanks for reporting this.

In version 3.0.0 I added support for Laravel 5.5.
