### ISSUE TITLE
Plugin Not Installing...Please Solve This

### ISSUE THREAD

**Issue by smacbca** [mplodowski/logout-plugin#12]
Today in new octobercms installation i try to install your logout plugin but when installing its shows error please fix this...
See attached image...
![logout_plugin_error](https://user-images.githubusercontent.com/30206756/30519301-7a9ddd02-9bb0-11e7-94b3-2cb1eb84fc3a.jpg)

Waiting for your response....

**Comment by mplodowski** [comment]
Plugin require Laravel 5.5 to work. Please enable `bleedingEdge` in `config/cms.php`and then update October to newest version if possible.

**Comment by smacbca** [comment]
i am already on latest version

**Comment by mplodowski** [comment]
You are probably on version 419, which uses Laravel 5.1. This plugin requires version 420+. I wrote you what you have to do to upgrade it.
